name: setup
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '14.17.0'
        cache: 'npm'
    - run: ./.github/scripts/update-npm.js
      shell: bash
    - run: npm install
      shell: bash
