name: ci
on:
  - push
  - pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: npm run lint:nofix
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build
  test:
    needs: build
    runs-on: ubuntu-latest
    env:
      DB_TESTING_PATH: "mongodb://localhost:27017/integrationTests"
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: '4.2'
      - name: Start backend
        run: |
          hash=$(node -p "crypto.randomBytes(32).toString('base64')")
          npm start -- -s $hash -c $DB_TESTING_PATH -p 8080 &
          sleep 1
        shell: bash
        
      - run: npm test
